### ISSUE TITLE
Use with 4 sensors

### ISSUE THREAD

**Issue by fab33** [chaveiro/EmonLibPro#1]
Can we use this library with 4 CT ? it's not clear ... And if it's possible what is the recommanded sample rate ?
Thanks.

**Comment by chaveiro** [comment]
Hi. Put in auto sample rate mode and test what it speed it attains. Technically it works in practice you will get a little low precision but should be ok.

**Comment by fab33** [comment]
It works fine. Thank you. Now I have to work on UNO R3+ETH+EmonTX Shield ... doesn't work even with jumper config.

**Comment by fab33** [comment]
I work agin on my sketch but I have a doubt for CalCoeff. Max value is 65535 but if I add 20076 to 60228, I'm out of range.

**Comment by chaveiro** [comment]
First sensor must be 0, last sensor must be < 65535.
Sensors in between must be incremental. usually you discover the value that best fits for the 2nd sensor and multiply by n sensor for the next. (given that all sensor hardware is the same)

**Comment by fab33** [comment]
And how we can find the "best" value ?
I try with resistive load and lot of turn of wire in CT but is not sufficient to have a "big" current.
And I found 2 "issues" : 
- Automatic samplerate doesn't work with 4 CT. I must mannualy set it (1600 for my tests)
- with 0 Power factor is 0.93 and with 65535 is 0.99 (it constantly growing when increasing CalCoef
With "default" value (20076), Pfact is 0.95
