### ISSUE TITLE
Compatible arduino board

### ISSUE THREAD

**Issue by fab33** [chaveiro/EmonLibPro#2]
It works on UNO but when I attemps to add espduino libraires, compiler warn me about low RAM (even with all my varaible with PROGMEM) and it doesn't work. Do you think it works on MEGA2560 or Due (with the last one it will be possible to add more inputs ...). Thank you.

**Comment by chaveiro** [comment]
If your don't need diagnostic features, comment //#define DIAG in lib header to lower memory footprint.
