### ISSUE TITLE
Reference volatge with MEGA2650

### ISSUE THREAD

**Issue by fab33** [chaveiro/EmonLibPro#3]
I can't get your library work on UNO with erther shield and emonTX shield but with MEGA, it works.
Just on little problem with CAL value (V1CAL for example).
I know with MEGA calibration is different (ie : http://forum.arduino.cc/index.php?topic=133907.0)
But I don't know how to modify your code to have a good reference.
for example without calibration I have #define V1CAL 731  and precision is not good.
Thank you for your help.

**Comment by fab33** [comment]
Finally I have the same problem with UNO. After investigate, this is harware problem. With Ethernet W5100 shield, on some boards A0 and A1 are used for SD card reader. Not very simple to solve because if you cut pin, Power shield can't send A0 and A1 to the board. And the W5100 need SPI connector to work ...
But you can close this issue, because it's not EmonlibPro related.

**Comment by chaveiro** [comment]
Nice, thanks for your feedback. :)
